blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('<int:post_id>/share/',
        views.post_share, name='post_share'),
    path('<int:post_id>/comment/',views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
# from django.db import models
# from django.utils import timezone
# # User чтобы создавать взаимосвязи между пользователями и постами
# from django.contrib.auth.models import User
# from taggit.managers import TaggableManager
# from django.urls import reverse

# # тут создаются классы для создания БД

# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         # возвращает набор запросов QuerySet
#         return super().get_queryset()\
#             .filter(status=Post.Status.PUBLISHED)

# class Post(models.Model):

#     class Status(models.TextChoices):
#         DRAFT = 'DF', "Черновик"
#         PUBLISHED = 'PB', 'Published'


#     title = models.CharField(max_length=200)
#     # должно быть уникальным для даты, сохраненной в поле publish.
#     slug = models.SlugField(max_length=250, unique_for_date='publish')
#     # Это поле определяет взаимосвязь многие-к-одному
#     author = models.ForeignKey(User, on_delete=models.CASCADE,
#                             related_name='blog_posts')

#     body = models.TextField()
#     publish = models.DateTimeField(default=timezone.now)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=2,
#                             choices=Status.choices,
#                             default=Status.DRAFT)

#     objects = models.Manager() # менеджер, применяемый по умолчанию
#     published = PublishedManager() # конкретно-прикладной менеджер
#     tags = TaggableManager()
#     class Meta:
#         ordering = ('-publish',)  # сортировка по дате
#         indexes = [models.Index(fields=['-publish']),
#                 ]

#     def __str__(self) -> str:
#         return self.title

#     def get_absolute_url(self):
#         """Возвращает URL для этой статьи."""
#         return reverse('blog:post_detail',
#                     args=[self.publish.year, self.publish.month,
#                         self.publish.day, self.slug])

# class Comment(models.Model):
#     # ForeignKey добавлено , чтобы связать каждый комментарий с 1 постом
#     post = models.ForeignKey(Post, on_delete=models.CASCADE,
#                             related_name='comments')
#     #
#     name = models.CharField(max_length=80)
#     email = models.EmailField()
#     body = models.TextField()
#     # хранить дату и время создания комментария.
#     created = models.DateTimeField(auto_now_add=True)
#     # позволит del неуместные комментарии вручную с по­мощью сайта администрирования
#     updated = models.DateTimeField(auto_now=True)
#     active = models.BooleanField(default=True)

#     class Meta:
#         # по умолчанию сортировать комментарии в хронологическом порядке
#         ordering = ['created']
#         indexes = [models.Index(fields=['created']),]

#     def __str__(self) -> str:
#         return f'Комментарий от {self.name} o {self.post}'

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                    .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                            choices=Status.choices,
                            default=Status.DRAFT)

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                    args=[self.publish.year,
                            self.publish.month,
                            self.publish.day,
                            self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
# from django import forms
# from .models import Comment

# class EmailPostForm(forms.Form):
#     # для имени человека, отправляющего пост
#     name = forms.CharField(max_length=25)
#     # адрес электронной почты человека, отправившего пост
#     email = forms.EmailField()
#     # используется адрес электронной почты получателя
#     to = forms.EmailField()
#     # для комментариев которые будут вставляться в электронное письмо
#     comments = forms.CharField(required=False, widget=forms.Textarea)


# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         # В форме CommentForm мы включили поля name, email и body в явном виде
#         fields = ['name', 'email', 'body']

from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                            widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

# для поискового запроса
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
# Count: общее количество объектов
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
# подключаем файл forms.py
from .forms import EmailPostForm, CommentForm, SearchForm
# Отправка электронных писем
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
# Для постраничной разбивки сайта
from django.views.generic import ListView
from taggit.models import Tag

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# поисковая строка
from django.contrib.postgres.search import TrigramSimilarity


# Представления(функции)
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    #
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Если номер_страницы не является целым числом, доставьте первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер_страницы выходит за пределы диапазона, доставьте последнюю страницу результатов
        posts = paginator.page(paginator.num_pages)
    return render(request,
                'blog/post/list.html',
                {'posts': posts,
                'tag': tag})

class PostListView(ListView):
    # чтобы иметь конкретно-прикладной набор запросов QuerySet
    queryset = Post.published.all()
    # используется для результатов запроса.
    context_object_name = 'posts'
    # Постраничная разбивка с 3 постами на страницу
    paginate_by = 3
    # шаблон используется для прорисовки страницы шаблоном template_name
    template_name = 'blog/post/list.html'


# Это представление детальной информации о посте
def post_detail(request, year, month, day, post):  #
    # извелекает посты по дате
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
    slug=post,
    publish__year=year,
    publish__month=month,
    publish__day=day)  # Указанная функция извлекает объект, соответствующий переданным параметрам, либо исключение HTTP с кодом состояния, равным 404

    # Список схожих постов
    # post_tags_ids = post.tags.values_list('id', flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)

    # similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
    #                             .order_by('-same_tags','-publish')[:4]

    # чтобы извлекать все активные комментарии к посту
    comments = post.comments.filter(active=True)
    # экземпляр формы для комментария
    form = CommentForm()

    # прорисовать извлеченный пост с использованием шаблона html
    return render(request, 'blog/post/detail.html', {'post': post,
                'comments': comments, 'form': form,
})

def post_share(request, post_id):
    # получаем объект поста по id
    post = get_object_or_404(Post, id=post_id, \
                                status=Post.Status.PUBLISHED)
    sent = False
    # для отправки email
    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # если форма валидна - отправляем уведомление
            cd = form.cleaned_data
            # отправить электронное письмо
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} рекомендует прочесть " \
                    f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'ulik345@yandex.ru',
                    [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
# require_POST, разрешить запросы методом POST только для этого представления
@require_POST
def post_comment(request, post_id):
    'чтобы управлять передачей поста на обработку.'
    # По id поста извлекается опубликованный пост
    post = get_object_or_404(Post, id=post_id,
                            status=Post.Status.PUBLISHED)

    # для хранения комментарного объекта при его создании.
    comment = None
    # экземпляр формы, используя переданные на обработку POST-данные
    form = CommentForm(data=request.POST)
    if form.is_valid():  # проводится их валидация
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Пост назначается созданному комментарию
        comment.post = post
        # Метод save() создает экземпляр модели, к которой форма
        # привязана и сохраняет его в базе данных
        comment.save()
    # Отобразить страницу с постом и формой для добав
    #ления комментария с ошибкой, если она есть
    return render(request, 'blog/post/comment.html',
                {'post': post, 'form': form, 'comment': comment})

# поисковая строка
def post_search(request):
    form = SearchForm()
    query = None
    results = []
#Для проверки того, что форма была передана на обработку
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', 'body', config='english')
            # выделяются основы слов и удаляются стоп-слова
            # search_query =  SearchQuery(query, config='english')
            # Получение всех публичных постов
            results = Post.published.annotate(
            # выполняется поиск опубликованных постов
                similarity=TrigramSimilarity('title', query),
                ).filter(similarity__gt=0.1).order_by('-similarity')
                # search=search_vector, rank=SearchRank(search_vector, search_query),
                # ).filter(search=search_query).order_by('-rank')

    return render(request,
                'blog/post/search.html',
                {'form': form,
                'query': query,
                'results': results})

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}


{% block title %}Добавить комментарий{% endblock %}

<!-- Это шаблон представления комментариев к посту -->
{% block content %}
<!--если данные формы валидны comment будет содержать созданный объект comment, и на страницу будет выведено сообщение об успехе -->
	{% if comment %}
	<h2>Ваш комментарий был добавлен</h2>
<p><a href="{{ post.get_absolute_url }}">Вернуться к сообщению</a></p>
<!--если данные формы невалидны, то переменной comment
будет назначено значение None. В этом случае мы отобразим коммен-
тарную форму. Для вставки созданного ранее шаблона comment_form.html  -->
{% else %}
	{% include 'blog/post/includes/comment_form.html' %}
	{% endif %}

	{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% comment %} для детальной инфы о посте {% endcomment %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<h1>{{ post.title }}</h1>
	<p class="date">
		Published {{ post.publish }} by {{ post.author }}
	</p>
{{ post.body|markdown }}
<p>
	<!-- добавлена ссылка на URL-адрес post_share -->
	<a href="{% url 'blog:post_share' post.id %}">
		Поделиться этим постом
	</a>
</p>
<!--  -->
	<h2>Похожие сообщения</h2>

	{% for post in similar_posts %}
	<p>
		<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</p>
	{% empty %}
	Подобных постов пока нет.
	{% endfor %}


	{% with comments.count as total_comments %}
	<h2>
<!-- фильтр pluralize, чтобы отображать суффикс множественного числа для слова comment -->
		{{ total_comments }} comment {{ total_comments|pluralize}}
	</h2>
	{% endwith %}
<!-- прокручивать комментарии к посту в цикле -->
{% for comment in comments %}
	<div class="comment">
		<p class="info">
			Комментарий {{ forloop.counter }} от {{ comment.name }}
			{{ comment.created }}
		</p>
		{{ comment.body|linebreaks}}
	</div>
	<!--Если список комментариев пуст,  -->
	{% empty %}
		<p>Нет комментариев.</p>
{% endfor %}
	{% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
<li>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
<!--тег extends сообщает Django, что надо наследовать от шаблона blog/base.html -->

{% block title %}My blog{% endblock %}

{% block content %}
<h1>My blog</h1>

	{% if tag %}
		<h2>Post tagged with '{{ tag.name }}'</h2>
	{% endif %}

	{% for post in posts %}
	<h2>
		<!--  -->
		<a href='{{ post.get_absolute_url }}'>
			{{ post.title }}
		</a>
	</h2>
	<p class="tags">
		Tags:
		{% for tag in post.tags.all %}
			<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
			{{ tag.name }}
			</a>
			{% if not forloop.last %}, {% endif %}
		{% endfor %}

	</p>
	<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
	{% comment %} truncatewords усекает значение до 30 {% endcomment %}
	{{ post.body|markdown|truncatewords_html:30 }}
	{% comment %} linebreaks конвертирует результат в разрывы строк в формате HTML {% endcomment %}
	{% endfor %}
	<!-- Шаблонный тег include загружает данный шаблон и прорисовывает его с использованием текущего контекста шаблона. Ключевое слово with используется для того, чтобы передавать дополнительные контекстные переменные в шаблон.
	Для прорисовки в шаблоне постраничной разбивки
	используется переменная page, при этом объект Page, который мы передаем из представления в шаблон, называется posts.-->
	{% include 'pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
<!-- для поискогвого запроса -->
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
    {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
    </h3>
    {% for post in results %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
        </a>
    </h4>
    {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
    <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
{% else %}
    <h1>Search for posts</h1>
    <form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
    </form>
{% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

<!-- Это шаблон, который используется для отображения формы, служащей
для того, чтобы делиться постом по электронной почте, и для отображения успешного сообщения после отправки электронного письма -->

{% block content %}

	{% if sent %}
	<h1>E-mail успешно отправлен</h1>
	<p>
		"{{ post.title }}" был успешно отправлен
		получателю {{ form.cleaned_data.to }}.
	</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail</h1>
		<form method="post">
			<!--Экземпляр формы вставлен с по­мощью тега form.as_p-->
			{{ form.as_p }}
	<!-- тег вводит скрытое поле с автоматически сгенерированным токеном во избежание атак -->
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
		</form>
	{% endif %}
{% endblock content %}